image: php:7.2

cache:
  paths:
    - vendor/

before_script:
  - apt-get update && apt-get install -y wget git
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"

build:
  script:
    - php composer.phar install
  artifacts:
    paths:
      - ./

test:
  dependencies:
    - build
  script:
    - ./vendor/bin/phpunit tests/